project_id = "ailhzwkcrvilqphweses"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080"]
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"

[db]
port = 54322

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[edge_runtime]
enabled = true
port = 54323

[functions.onedrive-sync]
verify_jwt = true

[analytics]
enabled = true