// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ailhzwkcrvilqphweses.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpbGh6d2tjcnZpbHFwaHdlc2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjgwNzUsImV4cCI6MjA2ODEwNDA3NX0.gpqv_5abJdZEDNh_GzRaPVKC8gJc8S2SglI2QD7XSpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});